# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CRON Test CI

on:
  schedule:
    - cron:  '0 6 * * *'    # At every day
jobs:
  build:

    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Notify slack success
      if: success()
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: corpo-product-scrapedin
        status: SUCCESS
        color: good
    - name: Notify slack fail
      if: failure()
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: corpo-product-scrapedin
        status: FAILED
        color: danger
    - name: Echo secrets
      run: |
          echo $COOKIE_FILE >> tests/cookie.json
          ls -la  tests/
      shell: bash
      env:
        # Feel free to rename this variable, but make sure to update it everywhere. You should paste your entire file in your secrets
        COOKIE_FILE : ${{secrets.COOKIE}}
    - run: npm ci
    - run: CI=true npm test
